[package]
name = "kemkem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
once_cell = "1.19.0"
rand = "0.8.5"
serde = "1.0.197"
sha3 = "0.10.8"
